// Stable diagnostic codes — see docs/SPECIFICATION.md §11.
export const CODES = {
  UNEXPECTED_CHARACTER: "E-LEX-001",
  UNTERMINATED_STRING: "E-LEX-002",
  BAD_ESCAPE: "E-LEX-003",
  RESERVED_WORD_AS_IDENTIFIER: "E-LEX-004",

  UNCLOSED_BLOCK: "E-PARSE-001",
  UNEXPECTED_END: "E-PARSE-002",
  DUPLICATE_ELSE: "E-PARSE-003",
  MALFORMED_FOR_EACH: "E-PARSE-004",
  MALFORMED_REPEAT: "E-PARSE-005",
  UNEXPECTED_TOKEN: "E-PARSE-006",

  UNDEFINED_NAME: "E-SEM-001",
  DUPLICATE_PROCEDURE: "E-SEM-002",
  REASSIGN_TYPE_MISMATCH: "E-SEM-003",
  OPERATOR_TYPE_ERROR: "E-SEM-004",
  RETURN_OUTSIDE_PROCEDURE: "E-SEM-005",
  CHANGE_UNDEFINED: "E-SEM-006",
  FOR_EACH_NOT_LIST: "E-SEM-007",
  REPEAT_COUNT_NOT_INTEGER: "E-SEM-008",
  ARITY_MISMATCH: "E-SEM-009",
  UNDEFINED_PROCEDURE: "E-SEM-010",
  EQUALITY_TYPE_MISMATCH: "E-SEM-011",

  DIVIDE_BY_ZERO: "E-RUN-001",
  NO_SUCH_FIELD: "E-RUN-002",
};
